Jairo b/section 1
JJBerdugo/swipe pull request #1
Opened 2023-07-18 02:59 UTC by JJBerdugo

Thank you so much for you thank you so much for walking with us on a very hard proyect. I don't refer to the BootCamp rather our life

2023-07-18 18:00 UTC, DanielCalleCO commented
Creo que aún no le has hecho push a tus últimos cambios. Revisa y me escribes nuevamente por favor

2023-07-19 00:07 UTC, JJBerdugo commented
@DanielCalleCO subi los cambios, si se puede ver ahora verdad?

2023-07-19 16:41 UTC, DanielCalleCO requested changes
Jairo, me gusta como se ve... si me permites un comentario, separa un poquito el texto del borde izquierdo, creo que es solo agregar un poquito de margin. De resto me gusta mucho!!

Revisa el comentario que te dejé por favor y vuelves a hacer push

![image](https://github.com/JJBerdugo/swipe/assets/100431019/bf115263-f12c-4569-907b-1dbfeb91013b)

2023-07-19 16:41 UTC, DanielCalleCO commented on index.html
> +                    <img src="/assets/logo-white.svg" alt="Logo-Swipe-img">
Jairito, creo que puedes quitar el `/` antes de cada assert. Si no, en otros equipo no se puede visualizar tu página correctamente.

2023-07-19 16:41 UTC, DanielCalleCO commented on index.html
> +                    <img src="/assets/zoom.png" alt="zoom-logo">
Jairo, faltaron todos estos "/" por quitar, de la linea 55 a la 62

2023-07-19 19:05 UTC, JJBerdugo commented on index.html
> +                    <img src="/assets/logo-white.svg" alt="Logo-Swipe-img">
Listo gracias profe ya lo quito y hago el push.

2023-07-19 19:06 UTC, DanielCalleCO approved these changes

2023-07-19 19:06 UTC, merged