Jairo b/section 4
JJBerdugo/swipe pull request #4
Opened 2023-07-23 22:59 UTC by JJBerdugo

this is section-4 to review

2023-07-23 23:01 UTC, DanielCalleCO commented
Te parece si pones estas imagenes en columna? 
![image](https://github.com/JJBerdugo/swipe/assets/100431019/5d166eaa-b0eb-4a36-ae3c-bd9955b346b4)

2023-07-23 23:02 UTC, DanielCalleCO requested changes
Pon las imagenes de la sección 2 en vertical en la resolución 320px y continuamos!

2023-07-23 23:16 UTC, JJBerdugo commented
listo profe asi??? 
![image](https://github.com/JJBerdugo/swipe/assets/113171870/10680e00-2add-47d4-b3af-5292037e416a)

2023-07-24 00:21 UTC, DanielCalleCO approved these changes
LGTM, felicitaciones Jairito!

2023-07-24 02:12 UTC, merged